default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: rails_app

test:
  <<: *default
  database: rails_app_test